### ISSUE TITLE
Dev Content Review 2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-reactive-messaging-rest#1]
- **What you’ll learn**
  - [x] "traditional RESTful" I doubt the word "traditional". Maybe remove it?
  - [x] in the diagram, "Request system property" and the arrow color give me a misleading feeling that it is not through message but rest call
    - suggest "Produce request messages" and "Consume request messages"
    - or "Produce request system property messages" and "Consume request system property messages"
- **Creating the system microservice**
  - [x] need to mention/explain and hotspot `@Incoming("getProperty")` and `@Outgoing("setProperty")`. It is the key of how rest trigger message and process the message.
- [x] May discuss with Laura whether can replace files instead of create. This guide is an extension of the reactive message guide and can focus on the triggering, no need to repeat some content same as the reactive message guide. It may affect the following sections:
  - **Creating the system microservice**
  - **Creating the inventory microservice**
  - **Configuring the MicroProfile Reactive Messaging connectors for Kafka**
  - **Configuring the server** (may no need to have this section)
  - **Building and running the application**
- **Configuring the server**
  - [x] format the following line in the inventory server.xml, so that not be wrapped
    - ` <httpEndpoint ... />`
- **Testing the application**
  - [x] No need to mention `http://localhost:9085/inventory/systems/{hostname}`

**Comment by ankitagrawa** [comment]
feedback addressed @gkwan-ibm
